### PR TITLE
🐛 Fix htpasswd command not found

### LINKED ISSUE #1485: E2e: htpasswd command not found
Add a script that ensures htpasswd is installed. This issue popped up after basic-auth was enabled in the e2e tests.

### PR DESCRIPTION
**Pull request by peppi-lotta**
**What this PR does / why we need it**:
Fixes #1485

### CODE REVIEW

File: hack/e2e/ensure_htpasswd.sh [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+
+set -eux
+
+# Check if htpasswd is installed and install it if not
+verify_htpasswd_version()
+{
+    if ! [ -x "$(command -v htpasswd)" ]; then
+        echo "htpasswd could not be found, installing..."
+        sudo apt-get update
+        sudo apt-get install -y apache2-utils
```
Comment (kashifest) [inline hack/e2e/ensure_htpasswd.sh:11]: not specific to this PR, but generally these `hack/e2e/` scripts wont work locally for a mac user like me. I will add an issue to make it work for other architectures as well. 
cc @lentzi90 @maxrantil

Comment (lentzi90) [reply hack/e2e/ensure_htpasswd.sh:11]: Yes it would be great to make this more flexible so it can work also for development and not just CI. So far my focus has been to just set up the CI, but for the long term I definitely intend to make this easier for developers to use locally.
I would ask that you do not make the CI unnecessarily complicated just to accommodate mac users though :wink:

**Review by lentzi90 — COMMENTED** [review]
/lgtm

File: hack/e2e/ensure_htpasswd.sh (hunk 1 above)
Comment (kashifest) [reply hack/e2e/ensure_htpasswd.sh:11]: I dis-asgree here. My understanding was the `hack/ `scripts are also used to test the CI test locally. If `hack/e2e` scripts are not meant to be used by developers locally, then I can agree. 

> I would ask that you do not make the CI unnecessarily complicated just to accommodate mac users though 😉

Comment (kashifest) [reply hack/e2e/ensure_htpasswd.sh:11]: Anyways, I have created an issue here anyhow https://github.com/metal3-io/baremetal-operator/issues/1487, lets discuss it on the issue.
/approve

File: hack/e2e/ensure_htpasswd.sh [hunk 2]
```diff
@@ -0,0 +1,15 @@
+#!/usr/bin/env bash
+
+set -eux
+
+# Check if htpasswd is installed and install it if not
+verify_htpasswd_version()
```
Comment (tuminoid) [inline hack/e2e/ensure_htpasswd.sh:6]: We're not actually verifying htpasswd version, but just its existence, so this function name is misleading.

```suggestion
verify_htpasswd()
```

File: hack/e2e/ensure_htpasswd.sh [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+{
+    if ! [ -x "$(command -v htpasswd)" ]; then
+        echo "htpasswd could not be found, installing..."
+        sudo apt-get update
+        sudo apt-get install -y apache2-utils
+    fi
+}
+
+verify_htpasswd_version
```
Comment (tuminoid) [inline hack/e2e/ensure_htpasswd.sh:15]:
```suggestion
verify_htpasswd
```

**Review by tuminoid — COMMENTED** [review]
Nit.

**Comment by tuminoid** [comment]
/hold
Please fix the nit.

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
/override test-ubuntu-integration-main
Irrelevant test for this.
